#!/usr/bin/env bash

source "${TOPLEVEL}/conf/common_settings.conf"

readonly BACKUP_MEASUREMENTS="${TOPLEVEL}/pipeline/backup_measurements.sh"
readonly BACKUP_LOCKFILE="${TOPLEVEL}/conf/backup.lock"
readonly BACKEDUP_MEAS_UUIDS="${TOPLEVEL}/conf/backedup_meas.txt"

readonly BACKUP_DISK="backups" # this name is known by ClickHouse
readonly BACKUP_LOCAL_DIR="/md1400-1b/backups"
readonly BACKUP_NFS_DIR="/backup/clickhouse-v1"
readonly BACKUP_NFS_USER="dioptra-data"
