#!/usr/bin/env bash

[[ -n "${__COMMON_SETTINGS__+x}" ]] && return
readonly __COMMON_SETTINGS__=""

readonly SECRETS_YML="${TOPLEVEL}/../infrastructure/secrets.yml"
readonly IRIS_USERNAME="iris@dioptra.io" # for parsing out IRIS_PASSWORD
readonly CLICKHOUSE_USERNAME="iris" # for parsing out CLICKHOUSE_PASSWORD
readonly CLICKHOUSE_DATABASE="iris"

readonly START_RED="\033[1;31m"
readonly START_BLUE="\033[1;34m"
readonly START_MAGENTA="\033[1;35m"
readonly END_COLOR="\033[0m"

readonly TIME=("/usr/bin/time" "--format" "real=%e user=%U sys=%S")
