#!/bin/bash

toplevel="$(git rev-parse --show-toplevel)"

#
# The measurement metadata file for all measurements.
#
readonly MEAS_MD_ALL_JSON="${toplevel}/cache/meas_md_all.json"

#
# The file with uuid of all scheduled measurements.
#
readonly MEAS_MD_METADATA_TXT="${toplevel}/cache/meas_md_metadata.txt"

# Variables related to datasets and tables
readonly BQ_PUBLIC_DATASET="iris_test"
readonly BQ_PRIVATE_DATASET="iris_test_1"
readonly GCP_PROJECT_ID="mlab-edgenet"
readonly BQ_TABLE="metadata"
readonly BQ_TMP_TABLE="metadata_tmp"

# metadata table schema
readonly SCHEMA_METADATA_JSON="${toplevel}/db/schema_metadata.json"
